// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYKxfC-J_gpHQP63x0SZoyMjsSNWqmE58',
    appId: '1:883919660011:web:cd93191945c12f55e3efae',
    messagingSenderId: '883919660011',
    projectId: 'film-91f87',
    authDomain: 'film-91f87.firebaseapp.com',
    storageBucket: 'film-91f87.appspot.com',
    measurementId: 'G-TTTCTSSJJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuTP1QhN-SxJluJOAQWg6taCfvdsu1diI',
    appId: '1:883919660011:android:65dc5c296b669d71e3efae',
    messagingSenderId: '883919660011',
    projectId: 'film-91f87',
    storageBucket: 'film-91f87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOiDHVJI_Wvn_RQ8_s4NyY3MirQADrlIE',
    appId: '1:883919660011:ios:6ee7c5571b744989e3efae',
    messagingSenderId: '883919660011',
    projectId: 'film-91f87',
    storageBucket: 'film-91f87.appspot.com',
    iosBundleId: 'com.example.flim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOiDHVJI_Wvn_RQ8_s4NyY3MirQADrlIE',
    appId: '1:883919660011:ios:6ee7c5571b744989e3efae',
    messagingSenderId: '883919660011',
    projectId: 'film-91f87',
    storageBucket: 'film-91f87.appspot.com',
    iosBundleId: 'com.example.flim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYKxfC-J_gpHQP63x0SZoyMjsSNWqmE58',
    appId: '1:883919660011:web:c4548de4d450854ce3efae',
    messagingSenderId: '883919660011',
    projectId: 'film-91f87',
    authDomain: 'film-91f87.firebaseapp.com',
    storageBucket: 'film-91f87.appspot.com',
    measurementId: 'G-L55949367K',
  );
}
